//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoBioenergia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentario
    {
        public int IDComentario { get; set; }
        public string Titulo { get; set; }
        public string Texto { get; set; }
        public int IDNoticia { get; set; }
        public int IDUtilizador { get; set; }
    
        public virtual Noticia Noticia { get; set; }
        public virtual Utilizador Utilizador { get; set; }
    }
}
