//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoBioenergia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noticia
    {
        public Noticia()
        {
            this.Comentario = new HashSet<Comentario>();
        }
    
        public int IDNoticia { get; set; }
        public string Titulo { get; set; }
        public System.DateTime Data { get; set; }
        public int IDUtilizador { get; set; }
        public int IDTopico { get; set; }
        public Nullable<int> IDPublicacao { get; set; }
    
        public virtual ICollection<Comentario> Comentario { get; set; }
        public virtual Topico Topico { get; set; }
    }
}
