//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoBioenergia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoFicheiro
    {
        public TipoFicheiro()
        {
            this.Anexo = new HashSet<Anexo>();
            this.Documento = new HashSet<Documento>();
        }
    
        public int IDFicheiro { get; set; }
        public string TipoFicheiro1 { get; set; }
    
        public virtual ICollection<Anexo> Anexo { get; set; }
        public virtual ICollection<Documento> Documento { get; set; }
    }
}
