//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoBioenergia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoAcesso
    {
        public TipoAcesso()
        {
            this.Utilizador = new HashSet<Utilizador>();
        }
    
        public int IDTAcesso { get; set; }
        public string Tipo { get; set; }
    
        public virtual ICollection<Utilizador> Utilizador { get; set; }
    }
}
