//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoBioenergia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topico
    {
        public Topico()
        {
            this.Noticia = new HashSet<Noticia>();
        }
    
        public int IDTopico { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<Noticia> Noticia { get; set; }
    }
}
